# ----
# Site

title: Ms. Whitby's Classroom
url: "https://mswhitby.com"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Online companion for Ms. Whitby's Computer Science course.
author:
  name: Deandra Whitby
  email: dwhitby@judsonisd.org
  twitter: # twitter username without the @ symbol
social:
  name: Edition Template
  links:
    - https://github.com/CloudCannon/edition-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.mdb
  - LICENCE
  - instructions.md

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

navigation:
  # - title: Courses
  #   url: /courses.html
  - title: Classes
    url: /classes.html
  - title: Resources
    url: /resources.html

# -----------
# CloudCannon

types:
  - minor
  - major

# -----------
# GitHub Primer Style

#sass:
#  # Where you keep your scss files
#  sass_dir: css/
#  # Where sass should look for other scss
#  load_paths:
#    - node_modules/